// This code was autogenerated with `dbus-codegen-rust -s -d net.hadess.SensorProxy -p /net/hadess/SensorProxy`, see https://github.com/diwic/dbus-rs
use dbus;
#[allow(unused_imports)]
use dbus::arg;
use dbus::blocking;

pub trait OrgFreedesktopDBusProperties {
    fn get(
        &self,
        interface_name: &str,
        property_name: &str,
    ) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error>;
    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error>;
    fn set(
        &self,
        interface_name: &str,
        property_name: &str,
        value: arg::Variant<Box<dyn arg::RefArg>>,
    ) -> Result<(), dbus::Error>;
}

#[derive(Debug)]
pub struct OrgFreedesktopDBusPropertiesPropertiesChanged {
    pub interface_name: String,
    pub changed_properties: arg::PropMap,
    pub invalidated_properties: Vec<String>,
}

impl arg::AppendAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn append(&self, i: &mut arg::IterAppend) {
        arg::RefArg::append(&self.interface_name, i);
        arg::RefArg::append(&self.changed_properties, i);
        arg::RefArg::append(&self.invalidated_properties, i);
    }
}

impl arg::ReadAll for OrgFreedesktopDBusPropertiesPropertiesChanged {
    fn read(i: &mut arg::Iter) -> Result<Self, arg::TypeMismatchError> {
        Ok(OrgFreedesktopDBusPropertiesPropertiesChanged {
            interface_name: i.read()?,
            changed_properties: i.read()?,
            invalidated_properties: i.read()?,
        })
    }
}

impl dbus::message::SignalArgs for OrgFreedesktopDBusPropertiesPropertiesChanged {
    const NAME: &'static str = "PropertiesChanged";
    const INTERFACE: &'static str = "org.freedesktop.DBus.Properties";
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target = T>> OrgFreedesktopDBusProperties
    for blocking::Proxy<'a, C>
{
    fn get(
        &self,
        interface_name: &str,
        property_name: &str,
    ) -> Result<arg::Variant<Box<dyn arg::RefArg + 'static>>, dbus::Error> {
        self.method_call(
            "org.freedesktop.DBus.Properties",
            "Get",
            (interface_name, property_name),
        )
        .and_then(|r: (arg::Variant<Box<dyn arg::RefArg + 'static>>,)| Ok(r.0))
    }

    fn get_all(&self, interface_name: &str) -> Result<arg::PropMap, dbus::Error> {
        self.method_call(
            "org.freedesktop.DBus.Properties",
            "GetAll",
            (interface_name,),
        )
        .and_then(|r: (arg::PropMap,)| Ok(r.0))
    }

    fn set(
        &self,
        interface_name: &str,
        property_name: &str,
        value: arg::Variant<Box<dyn arg::RefArg>>,
    ) -> Result<(), dbus::Error> {
        self.method_call(
            "org.freedesktop.DBus.Properties",
            "Set",
            (interface_name, property_name, value),
        )
    }
}

pub trait OrgFreedesktopDBusIntrospectable {
    fn introspect(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target = T>>
    OrgFreedesktopDBusIntrospectable for blocking::Proxy<'a, C>
{
    fn introspect(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Introspectable", "Introspect", ())
            .and_then(|r: (String,)| Ok(r.0))
    }
}

pub trait OrgFreedesktopDBusPeer {
    fn ping(&self) -> Result<(), dbus::Error>;
    fn get_machine_id(&self) -> Result<String, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target = T>> OrgFreedesktopDBusPeer
    for blocking::Proxy<'a, C>
{
    fn ping(&self) -> Result<(), dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "Ping", ())
    }

    fn get_machine_id(&self) -> Result<String, dbus::Error> {
        self.method_call("org.freedesktop.DBus.Peer", "GetMachineId", ())
            .and_then(|r: (String,)| Ok(r.0))
    }
}

pub trait NetHadessSensorProxy {
    fn claim_accelerometer(&self) -> Result<(), dbus::Error>;
    fn release_accelerometer(&self) -> Result<(), dbus::Error>;
    fn claim_light(&self) -> Result<(), dbus::Error>;
    fn release_light(&self) -> Result<(), dbus::Error>;
    fn claim_proximity(&self) -> Result<(), dbus::Error>;
    fn release_proximity(&self) -> Result<(), dbus::Error>;
    fn has_accelerometer(&self) -> Result<bool, dbus::Error>;
    fn accelerometer_orientation(&self) -> Result<String, dbus::Error>;
    fn has_ambient_light(&self) -> Result<bool, dbus::Error>;
    fn light_level_unit(&self) -> Result<String, dbus::Error>;
    fn light_level(&self) -> Result<f64, dbus::Error>;
    fn has_proximity(&self) -> Result<bool, dbus::Error>;
    fn proximity_near(&self) -> Result<bool, dbus::Error>;
}

impl<'a, T: blocking::BlockingSender, C: ::std::ops::Deref<Target = T>> NetHadessSensorProxy
    for blocking::Proxy<'a, C>
{
    fn claim_accelerometer(&self) -> Result<(), dbus::Error> {
        self.method_call("net.hadess.SensorProxy", "ClaimAccelerometer", ())
    }

    fn release_accelerometer(&self) -> Result<(), dbus::Error> {
        self.method_call("net.hadess.SensorProxy", "ReleaseAccelerometer", ())
    }

    fn claim_light(&self) -> Result<(), dbus::Error> {
        self.method_call("net.hadess.SensorProxy", "ClaimLight", ())
    }

    fn release_light(&self) -> Result<(), dbus::Error> {
        self.method_call("net.hadess.SensorProxy", "ReleaseLight", ())
    }

    fn claim_proximity(&self) -> Result<(), dbus::Error> {
        self.method_call("net.hadess.SensorProxy", "ClaimProximity", ())
    }

    fn release_proximity(&self) -> Result<(), dbus::Error> {
        self.method_call("net.hadess.SensorProxy", "ReleaseProximity", ())
    }

    fn has_accelerometer(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "net.hadess.SensorProxy",
            "HasAccelerometer",
        )
    }

    fn accelerometer_orientation(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "net.hadess.SensorProxy",
            "AccelerometerOrientation",
        )
    }

    fn has_ambient_light(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "net.hadess.SensorProxy",
            "HasAmbientLight",
        )
    }

    fn light_level_unit(&self) -> Result<String, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "net.hadess.SensorProxy",
            "LightLevelUnit",
        )
    }

    fn light_level(&self) -> Result<f64, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "net.hadess.SensorProxy",
            "LightLevel",
        )
    }

    fn has_proximity(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "net.hadess.SensorProxy",
            "HasProximity",
        )
    }

    fn proximity_near(&self) -> Result<bool, dbus::Error> {
        <Self as blocking::stdintf::org_freedesktop_dbus::Properties>::get(
            self,
            "net.hadess.SensorProxy",
            "ProximityNear",
        )
    }
}
